---
- name: cloudflare_api_creds_should_be_set
  assert:
    that:
      - cloudflare_api_email is defined
      - cloudflare_api_key is defined

- name: create_docker_network_external_isolated_traefik
  docker_network:
    name: external_isolated_traefik
    attachable: true
    ipam_config:
      - subnet: "{{ traefik_net_external_isolated_subnet }}"
    driver_options:
      com.docker.network.traefik.enable_icc: false
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0

- name: create_traefik_data_volume
  docker_volume:
    name: "{{ traefik_data_volume }}"

- name: make_config_dir
  file:
    path: "{{ traefik_confdir_host }}"
    state: directory
    mode: 0755

- name: template_api
  template:
    src: "{{ traefik_api_config }}.j2"
    dest: "{{ traefik_confdir_host }}/{{ traefik_api_config }}"
    mode: 0660

- name: template_services
  template:
    src: "service-generic.yml.j2"
    dest: "{{ traefik_confdir_host }}/service-{{ item.name }}.yml"
    mode: 0660
  loop: "{{ traefik_services }}"

- name: template_tcp_services
  template:
    src: "service-tcp.yml.j2"
    dest: "{{ traefik_confdir_host }}/service-tcp-{{ item.name }}.yml"
    mode: 0660
  loop: "{{ traefik_tcp_services }}"

- name: create_traefik_container
  docker_container:
    name: "{{ traefik_host }}"
    image: "{{ traefik_image }}"
    pull: true
    restart_policy: always
    hostname: "{{ traefik_host }}"
    published_ports:
      - "{{ traefik_host_http_port }}:80"
      - "{{ traefik_host_https_port }}:443"
      - "127.0.0.1:{{ traefik_host_api_port }}:8080"
      - "{{ traefik_host_terraria_port }}:7777"
    volumes:
      - "{{ traefik_data_volume }}:{{ traefik_data_mount }}"
      - "{{ traefik_confdir_host }}:{{ traefik_confdir_mount }}"
    command:
      - "--providers.file.directory={{ traefik_confdir_mount }}"
      - "--providers.file.watch=true"
      - "--entrypoints.http.address=':80'"
      - "--entrypoints.https.address=':443'"
      - "--entrypoints.api.address=':8080'"
      - "--entrypoints.terraria.address=':7777'"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider\
        =cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers\
        ='1.1.1.1:53'"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delayBeforeCheck\
        =180"
      - "--certificatesresolvers.cloudflare.acme.storage\
        ={{ traefik_data_mount }}/acme.json"
      - "--certificatesresolvers.cloudflare.acme.email\
        ={{ cloudflare_api_email }}"
      - "--certificatesresolvers.cloudflare.acme.caserver\
        ='{{ traefik_acme_caserver }}'"
      - "--api=true"
      - "--log.level={{ traefik_log_level }}"
    networks: "{{ traefik_default_nets | union(traefik_extra_nets) }}"
    networks_cli_compatible: true  # hide deprecation warning
    network_mode: "external_isolated_traefik"  # hide deprecation warning
    env:
      CF_API_EMAIL: "{{ cloudflare_api_email }}"
      CF_API_KEY: "{{ cloudflare_api_key }}"
