---
- name: create_sogo_network
  docker_network:
    name: sogo_network
    ipam_config:
      - subnet: "{{ sogo_net_subnet }}"
        gateway: "{{ sogo_net_gw }}"
        iprange: "{{ sogo_net_iprange }}"

# TODO: permanent storage for mariadb needed
- name: create_mariadb_container
  docker_container:
    name: "{{ mariadb_host }}"
    image: mariadb
    restart_policy: always
    hostname: "{{ mariadb_host }}"
    exposed_ports: "{{ mariadb_port }}"
    networks:
      - name: sogo_network
        ipv4_address: "{{ mariadb_ip }}"
        aliases:
          - "{{ mariadb_host }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_pass }}"
      MYSQL_DATABASE: "{{ mariadb_name }}"
      MYSQL_USER: "{{ mariadb_user }}"
      MYSQL_PASSWORD: "{{ mariadb_pass }}"

- name: create_sogo_container
  docker_container:
    name: "{{ sogo_host }}"
    image: cha87de/sogo
    restart_policy: always
    hostname: "{{ sogo_host }}"
    ports:
      - "{{ sogo_http_external_port }}:{{ sogo_http_internal_port }}"
    networks:
      - name: sogo_network
        ipv4_address: "{{ sogo_ip }}"
        aliases:
          - "{{ sogo_host }}"
        links:
          - "{{ mariadb_host }}"
    env:
      DB_HOST: "{{ mariadb_host }}"
      DB_USER: "{{ mariadb_user }}"
      DB_PASS: "{{ mariadb_pass }}"
      DB_DATABASE: "{{ mariadb_name }}"
      DB_USERPROFILES: "mysql://{{ mariadb_user }}:{{ mariadb_pass }}\
        @{{ mariadb_host }}:{{ mariadb_port }}/{{ mariadb_name }}\
        /{{ mariadb_user }}_user_profile"
      DB_FOLDERINFO: "mysql://{{ mariadb_user }}:{{ mariadb_pass }}\
        @{{ mariadb_host }}:{{ mariadb_port }}/{{ mariadb_name }}\
        /{{ mariadb_user }}_folder_info"
      DB_SESSIONSFOLDER: "mysql://{{ mariadb_user }}:{{ mariadb_pass }}\
        @{{ mariadb_host }}:{{ mariadb_port }}/{{ mariadb_name }}\
        /{{ mariadb_user }}_sessions_folder"
      DB_USERVIEW: "mysql://{{ mariadb_user }}:{{ mariadb_pass }}\
        @{{ mariadb_host }}:{{ mariadb_port }}/sogo/{{ mariadb_user }}_view"
      IMAP_SERVER: "{{ sogo_imap_server }}"
      SIEVE_SERVER: "{{ sogo_sieve_server }}"
      SMTP_SERVER: "{{ sogo_smtp_server }}"
      MAILDOMAIN: "{{ sogo_mail_domain }}"
      TITLE: "{{ sogo_title }}"
      LANGUAGE: "{{ sogo_lang }}"
      TIMEZONE: "{{ sogo_tz }}"
      SUPERUSERS: "{{ sogo_superusers }}"
