---
rst_backup_cmd: >-
  dpkg --get-selections > /to_backup/dpkg_selections.list ;
  ionice -c2 -n7 restic backup --one-file-system
  --files-from {{ restic_config_path }}/includes
  --exclude-file {{ restic_config_path }}/excludes

restic_repos:
  - name: sftp-home-workstation1
    url: sftp:home-workstation1@home-server1:/backup/home-workstation1
    password: "{{ rst_backup_home_workstation1_pass }}"
    jobs:
      - command: "{{ rst_backup_cmd }}"
        at: '0 13 * * *'
    retention_time: '0 14 * * *'
    retention:
      daily: 14
      weekly: 13
      tags:
        - keep
  - name: b2-home-workstation1
    url: "b2:home-workstation1:backup/home-workstation1"
    password: "{{ rst_backup_home_workstation1_pass }}"
    remote_credentials:
      b2_account_id: "{{ rst_backup_home_workstation1_b2_id }}"
      b2_account_key: "{{ rst_backup_home_workstation1_b2_key }}"
    jobs:
      - command: "{{ rst_backup_cmd }}"
        at: '30 13 * * *'
    retention_time: '30 14 * * *'
    retention:
      daily: 14
      weekly: 13
      tags:
        - keep

restic_includes_files:
  - filename: includes
    includes: |
      /config
      /home
      /root
      /var/local
      /usr/local/bin
      /usr/local/etc
      /var/lib/docker/volumes
      /var/lib/libvirt/images
      /etc
      /to_backup

restic_excludes_files:
  - filename: excludes
    excludes: |
      **/*.nobackup
      **/*backup
      **/*.bak
      **/.Trash
      **/*cache
      **/*Cache
      **/*CACHE
      **/*tmp
      **/*Tmp
      **/*TMP
      **/*temp
      **/*Temp
      **/*TEMP
      **/*log
      **/*Log
      **/*LOG
      /home/*/Downloads*
      /home/*/Nextcloud
      /home/*/opt
      /home/*/mnt
      /home/*/.local
      /home/*/.thumbnails
      /home/*/.ansible
      /home/*/.vagrant.d/boxes
      /home/*/.wine
      /home/*/.cargo
      /home/*/.gem
      /home/*/.go
      /home/*/.golang
      /home/*/.node_modules
      /home/*/.npm
      /home/*/.var
      /home/*/go
      /home/*/snap
      /root/Downloads*
      /root/Nextcloud
      /root/opt
      /root/mnt
      /root/.local
      /root/.thumbnails
      /root/.ansible
      /root/.vagrant.d/boxes
      /root/.wine
      /root/.cargo
      /root/.gem
      /root/.go
      /root/.golang
      /root/.node_modules
      /root/.npm
      /root/.var
      /root/go
      /root/snap
