---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 1536
      cpus: 4

platforms:
  - name: instance
    box: generic/ubuntu1804
    provider_raw_config_args:
      - 'cpu_mode = "custom"'
      - 'cpu_model = "qemu64"'

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

provisioner:
  name: ansible
  options:
    extra-vars:
      cloudflare_api_email: "$CLOUDFLARE_API_EMAIL"
      cloudflare_api_key: "$CLOUDFLARE_API_KEY"
      traefik_log_level: DEBUG

verifier:
  name: ansible
  options:
    no-flaky-report: true
