---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 1536
      cpus: 4

lint:
  name: yamllint

platforms:
  - name: instance
    box: generic/ubuntu1804
    provider_raw_config_args:
      - 'cpu_mode = "custom"'
      - 'cpu_model = "qemu64"'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    extra-vars:
      cloudflare_api_email: "$CLOUDFLARE_API_EMAIL"
      cloudflare_api_key: "$CLOUDFLARE_API_KEY"

verifier:
  name: testinfra
  lint:
    name: flake8
