---
traefik_image: traefik:v2.1

traefik_host: traefik
traefik_net_external_isolated_subnet: 172.10.70.0/24
traefik_net_external_isolated_ip: 172.10.70.2
traefik_host_http_port: 80
traefik_host_https_port: 443
traefik_host_api_port: 8080
# traefik_host_terraria_port: 7777

# format as in `docker_container` module, `networks:` parameter
traefik_extra_nets: []
#   - name: othernet
#     ipv4_address: 127.0.0.99

traefik_api_auth_user: admin
# default pass: CHANGEME. Generate new hash with:
# `htdigest -c >(cat | cut -d':' -f3) traefik $USERNAME`
traefik_api_auth_hash: bfd5f4c74bc7047108bc3f6c91b3f4fa

traefik_log_level: INFO
traefik_confdir_host: /config/traefik
traefik_acme_caserver: https://acme-staging-v02.api.letsencrypt.org/directory

traefik_services:
  - name: service1
    http: true
    https: true
    http_to_https: false
    url: http://172.10.71.3:80
    rule: "Host(`service1.example.org`)"

traefik_tcp_services: []
  # - name: terraria
  #   ip: 172.10.71.3
  #   port: 7777

traefik_redirect_services:
  - name: root
    rule: "Host(`lesikov.com`)"
    regex: "https?://lesikov.com/?(.*)"
    replacement: "https://ilya-lesikov.com/$1"
    permanent: true
