---
- name: Install jq
  apt:
    name: jq
    update_cache: true

- name: Create docker network internal_nextcloud
  docker_network:
    name: "{{ nxc_net_name }}"
    attachable: true
    ipam_config:
      - subnet: "{{ nxc_net_internal_subnet }}"
    driver_options:
      com.docker.network.nextcloud.enable_icc: true

- name: Create nextcloud data volume
  docker_volume:
    name: "{{ nxc_volume_data }}"

- name: Create nextcloud container
  docker_container:
    name: "{{ nxc_host }}"
    image: "{{ nxc_image }}"
    pull: true
    restart_policy: always
    hostname: "{{ nxc_host }}"
    volumes:
      - "{{ nxc_volume_data }}:{{ nxc_data_mount }}"
    networks:
      - name: "{{ nxc_net_name }}"
        ipv4_address: "{{ nxc_ip }}"
        aliases: "{{ nxc_host }}"
    networks_cli_compatible: true  # hide deprecation warning
    network_mode: "{{ nxc_net_name }}"  # hide deprecation warning
