---
- name: Converge
  hosts: all
  become: true
  tasks:
    - import_role:
        name: geerlingguy.docker
    - import_role:
        name: nextcloud-dockerized
    - import_role:
        name: nextcloud-dockerized
        tasks_from: setup.yml
